name: Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt install g++ cmake libsdl2-dev libglm-dev
        
        sudo git clone https://github.com/skypjack/entt.git
        cd entt
        sudo mkdir out
        cd out
        
        sudo cmake ..
        sudo cmake --install .
        
        cd ../../
        sudo mkdir out
        cd out
        
        sudo cmake ..
        sudo cmake --build . --target install
