
name: Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install cmake libglm-dev
        
        git clone https://github.com/libsdl-org/SDL
        cd SDL
        mkdir build
        cd build
        ../configure
        make
        sudo make install
        cd ../..
        
        sudo git clone https://github.com/skypjack/entt.git
        cd entt
        cd build
        
        sudo cmake ..
        sudo cmake --install .
        
        cd ../../
        sudo mkdir build
        cd build
        
        sudo cmake ..
        sudo cmake --build . --target install
        sudo cmake -DBUILD_TESTS=ON ..
        sudo cmake --build . --target install
 
