name: Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        apt install g++ cmake libsdl2-dev libglm-dev
        
        git clone https://github.com/skypjack/entt.git
        cd entt
        mkdir out
        cd out
        
        cmake ..
        cmake --install .
        
        cd ../../
        mkdir out
        cd out
        
        cmake ..
        cmake --build . --target install
