
name: Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install cmake libsdl2-dev libglm-dev pkg-config
        
        sudo pkg-config --libs sdl2
        
        sudo git clone https://github.com/skypjack/entt.git
        cd entt
        cd build
        
        sudo cmake ..
        sudo cmake --install .
        
        cd ../../
        sudo mkdir build
        cd build
        
        sudo cmake -DBUILD_TESTS=ON ..
        sudo cmake --build . --target install
 
