name: Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install g++ cmake gdebi-core
        
        curl -L "http://mirrors.kernel.org/ubuntu/pool/universe/libs/libsdl2/libsdl2-dev_2.0.14+dfsg2-3_amd64.deb" -o sdl2-dev.deb
        curl -L "http://mirrors.kernel.org/ubuntu/pool/main/libs/libsdl2/libsdl2-2.0-0_2.0.14+dfsg2-3_amd64.deb" -o sdl2.deb
        sudo gdebi sdl2.deb
        sudo gdebi sdl2-dev.dev
        sudo rm sdl2.deb
        sudo rm sdl2-dev.deb
        
        sudo ../configure
        sudo cmake --build . --target install
        
        cd ../../
        
        sudo git clone https://github.com/skypjack/entt.git
        cd entt
        sudo mkdir build
        cd build
        
        sudo cmake ..
        sudo cmake --install .
        
        cd ../../
        sudo mkdir build
        cd build
        
        sudo cmake -DBUILD_TESTS=ON ..
        sudo cmake --build . --target install
